---
title: "Invasive Newts Landscape Genetics"
author: "Bernardo Antunes"
format: html
editor: visual
---

## Genetic data

We first define the study areas based on the presumed release sites of *Triturus carnifex* and localities with available genetic data. Specifically, we delineate each study area as a circle extending 2 km beyond the maximum distance between release sites and genetic sampling localities. Here we also set the coordinate reference systems to be used for the geospatial analyses throughout the work. See `scripts/R/01-create_study_areas.R`

## Environmental data

To capture environmental variables potentially relevant to the invasion process of *T. carnifex*, we collected data from [Landsat 5](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LT05_C02_T1_L2) and compiled three indices representing distinct components of the environment: a vegetation greenness index (NDVI, Normalized Difference Vegetation Index), a surface water/moisture index (MNDWI, Modified Normalized Difference Water Index), and a bare soil exposure index (BSI, Bare Soil Index). For each index, we calculated the per-pixel median across the newts breeding season (March–July) for each year from 1985 to 2011, yielding a single annual composite per index. These annual composites were then combined across years into an overall median per index, representing typical environmental conditions over the study period. To characterize landscape change, we also estimated the intensity and direction of the temporal trend for each index. These variables were collected at a spatial resolution of 30 m. See `scripts/python/02-collect_environmental_data_La`

To characterize topography, we obtained a [digital elevation model](https://developers.google.com/earth-engine/datasets/catalog/NASA_NASADEM_HGT_001) (DEM), from which we derived slope, aspect, Topographic Position Index (TPI), and Terrain Ruggedness Index (TRI). These variables were used to capture elevation, terrain steepness and orientation, local topographic position (e.g., ridges and valleys), and terrain heterogeneity, respectively. These variables were collected at a spatial resolution of 30 m. See `scripts/python/03-collect_environmental_data_NASA_DEM.py`

To further characterize the landscape we collected land-cover variables in a binary (presence-absence) format from [ELC10](https://gee-community-catalog.org/projects/elc/#earth-engine-snippet) at a spatial resolution of 10 m. These variables were then projected to 30 m to match the rest of the variables, and in the process converted to continuous format (0 to 100 %). See `scripts/python/04-collect_environmental_data_Landcover.py` and `scripts/R/05-process_environmental_data.R`

## Landscape genetics

Having both genetic and environmental data, we start with the landscape genetic workflow. The first task being estimating Euclidean geographic distances from the presumed release sites for each population locality with available genetic data. See `scripts/R/06-collect_distances_from_release_sites.R`

Then we follow to create the baseline models that take into account only distance from release sites, time since release, and/or region as a random variable.

Include Region and distance from release seems to result in the best models. The question is can we build a model that predicts well across regions? So a model that excludes that variable but gets to the same performance?

Model from region is clearly better! time for introduction does not explain so well the differences...

A parametric sigmoid model woul be more useful for later interpreations... HZAR package, maybe ask Tomek or Wiesiek.
